#!/bin/bash

COMMAND=$1

export DELTA_CMD=delta
export DELTA_DIFFFILTER="delta --color-only"
export DELTA_DARK=true
export DELTA_NAVIGATE=true
export DELTA_SIDEBYSIDE=false
export DELTA_LINENUMBERS=true
export BLAME_CODE_STYLE=syntax
export BLAME_PALETTE="#55007f #7f007f #7f7f00 #aa0044 #44aa00 #0044aa #007f7f #007f00"
export BLAME_FORMAT="{commit:<8} {timestamp:<16} {author:<18}"
export BLAME_TIME_FORMAT="%Y-%m-%d %H:%M"


do_delta()
{
    filtered_args=()
    for _arg in "$@"; do
        if [[ "$_arg" != +* ]]; then
            filtered_args+=("$_arg")
        fi
    done

    git --config-env=core.pager=DELTA_CMD \
        --config-env=interactive.diffFilter=DELTA_DIFFFILTER \
        --config-env=delta.navigate=DELTA_NAVIGATE  \
        --config-env=delta.dark=DELTA_DARK \
        --config-env=delta.side-by-side=DELTA_SIDEBYSIDE \
        --config-env=delta.line-numbers=DELTA_LINENUMBERS \
        --config-env=delta.blame-code-style=BLAME_CODE_STYLE \
        --config-env=delta.blame-palette=BLAME_PALETTE \
        --config-env=delta.blame-format=BLAME_FORMAT \
        --config-env=delta.blame-timestamp-output-format=BLAME_TIME_FORMAT \
        ${filtered_args[@]}
    exit 0
}

do_tig()
{
    # Ref: https://jonas.github.io/tig/doc/tig.1.html
    export XDG_CONFIG_HOME=~/.config/helix
    _cmd=$1
    if [ "$_cmd" == log ]; then
        shift
        tig $@
    else
        tig $@
    fi
    exit 0
}

do_git()
{
    _cmd=$1
    if [ "$_cmd" == log ]; then
        git $@ --pretty=format:"%h - %an %ae, %ar : %s"
    else
        git $@
    fi
    exit 0
}

do_delta_first()
{
    if command -v delta 2>/dev/null ; then
        do_delta $@
    elif command -v tig 2>/dev/null ; then
        do_tig $@
    else
        do_git $@
    fi
}

do_tig_first()
{
    if command -v tig 2>/dev/null ; then
        do_tig $@
    elif command -v delta 2>/dev/null ; then
        do_delta $@
    else
        do_git $@
    fi

}


case $COMMAND in
    diff|show)
        do_delta_first $@
        ;;
    blame|log)
        do_tig_first $@
        ;;
    status|grep)
        do_git $@
        ;;
    *)
        do_git $@
        ;;
esac
