#!/bin/bash
#
# https://zenn.dev/spacemarket/articles/192a58e9177961
#

tempfile=$(mktemp)
if command yazi 2>/dev/null; then
    yazi --chooser-file="$tempfile" $@
else
    dir=$(dirname $1 2>/dev/null)
    filepath=$(basename $1 2>/dev/null)
    if [ -n "$filepath" ] && [ -n "$dir" ]; then
        tree -C "$dir" | less -r "+/$filepath" -j 5
    else
        tree -C | less -r
    fi
fi

if [[ -s "$tempfile" ]]; then
    paths=$(cat "$tempfile")

    # For the "search://" format, extract the actual path.
    if [[ "$paths" == search://* ]]; then
        paths=$(echo "$paths" | sed 's|search://[^/]*/||')
    fi

    rm -f "$tempfile"
    zellij action toggle-floating-panes
    zellij action write 27
    zellij action write-chars ":open \"$paths\""
    zellij action write 13
else
    rm -f "$tempfile"
    zellij action toggle-floating-panes
fi
