#!/bin/bash
#
# https://zenn.dev/spacemarket/articles/192a58e9177961
#

tempdir=""
tempfile=""
if command -v yazi >/dev/null 2>&1; then
    tempfile=$(mktemp)
    yazi --chooser-file="$tempfile" $@
elif [ -x ~/.config/helix/fff ]; then
    tempdir=$(mktemp -d)
    tempfile=${tempdir}/fff/opened_file
    XDG_CACHE_HOME=${tempdir} ~/.config/helix/fff -p $(dirname $@ 2>/dev/null)
else
    dir=$(dirname $1 2>/dev/null)
    filepath=$(basename $1 2>/dev/null)
    if [ -n "$filepath" ] && [ -n "$dir" ]; then
        tree -C "$dir" | less -r "+/$filepath" -j 5
    else
        tree -C | less -r
    fi
fi

if [[ -f "$tempfile" ]]; then
    paths=$(cat "$tempfile")

    # For the "search://" format, extract the actual path.
    if [[ "$paths" == search://* ]]; then
        paths=$(echo "$paths" | sed 's|search://[^/]*/||')
    fi

    rm -f "$tempfile"
    [[ -d "$tempdir" ]] && rm -rf "$tempdir"
    zellij action toggle-floating-panes
    zellij action write 27
    zellij action write-chars ":open \"$paths\""
    zellij action write 13
else
    [[ -f "$tempfile" ]] && rm -f "$tempfile"
    [[ -d "$tempdir" ]] && rm -rf "$tempdir"
    zellij action toggle-floating-panes
fi
